// <auto-generated />
using EFCoreKeylessEntityTypes.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCoreKeylessEntityTypes.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200528173757_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EFCoreKeylessEntityTypes.Entities.QLink", b =>
                {
                    b.Property<string>("QNumber")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("QGroup")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("QNumber");

                    b.ToTable("QLink");
                });

            modelBuilder.Entity("EFCoreKeylessEntityTypes.Entities.SalesOrders", b =>
                {
                    b.Property<string>("SalesOrder")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("QLinkQNumber")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("QNumber")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("SalesOrder");

                    b.HasIndex("QLinkQNumber");

                    b.ToTable("SalesOrders");
                });

            modelBuilder.Entity("EFCoreKeylessEntityTypes.Entities.SalesOrdersItems", b =>
                {
                    b.Property<string>("SalesOrderItem")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<decimal>("OrderQuantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PartNumber")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("SalesOrderID")
                        .HasColumnName("SalesOrder")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<int>("UHeight")
                        .HasColumnType("int");

                    b.HasKey("SalesOrderItem");

                    b.HasIndex("SalesOrderID");

                    b.ToTable("SalesOrdersItems");
                });

            modelBuilder.Entity("EFCoreKeylessEntityTypes.Entities.SalesOrders", b =>
                {
                    b.HasOne("EFCoreKeylessEntityTypes.Entities.QLink", "QLink")
                        .WithMany()
                        .HasForeignKey("QLinkQNumber");
                });

            modelBuilder.Entity("EFCoreKeylessEntityTypes.Entities.SalesOrdersItems", b =>
                {
                    b.HasOne("EFCoreKeylessEntityTypes.Entities.SalesOrders", "SalesOrder")
                        .WithMany("SalesOrdersItems")
                        .HasForeignKey("SalesOrderID");
                });
#pragma warning restore 612, 618
        }
    }
}
